# Generated by Django 4.0.3 on 2022-03-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_alter_patient_sex_alter_treatment_dosage_per_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='blood',
            field=models.TextField(blank=True, choices=[('O+ve', 'O+ve'), ('O-ve', 'O-ve'), ('A-ve', 'A-ve'), ('A+ve', 'A+ve'), ('AB+ve', 'AB+ve'), ('AB-ve', 'AB-ve'), ('B-ve', 'B-ve'), ('B+ve', 'B+ve')], null=True),
        ),
    ]
