# Generated by Django 3.2.12 on 2022-03-04 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
