# Generated by Django 4.0.3 on 2022-03-26 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('department', models.TextField(blank=True, null=True)),
                ('roll_no', models.IntegerField(blank=True, null=True, unique=True)),
                ('dob', models.TextField(blank=True, null=True)),
                ('doj', models.TextField(blank=True, null=True)),
                ('contact', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.TextField(blank=True, null=True)),
                ('english', models.IntegerField(blank=True, null=True)),
                ('maths', models.IntegerField(blank=True, null=True)),
                ('language', models.IntegerField(blank=True, null=True)),
                ('social', models.IntegerField(blank=True, null=True)),
                ('biology', models.IntegerField(blank=True, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myrecords.student')),
            ],
        ),
    ]
