# Generated by Django 4.0.3 on 2022-03-26 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myrecords', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='rank',
        ),
    ]
