# Generated by Django 3.2.12 on 2022-03-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_img',
            field=models.ImageField(null=True, upload_to='task_img'),
        ),
    ]
