# Generated by Django 3.2.12 on 2022-03-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0002_task_task_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_img',
            field=models.ImageField(blank=True, null=True, upload_to='task_img'),
        ),
    ]
